language: ruby
cache:
- bundler
install:
- bundle install
rvm:
- 2.0
- 2.1
- 2.2
- 2.3.0
- 2.4.1
notifications:
  email:
    recipients:
    - sensu-plugin@sensu-plugins.io
    on_success: change
    on_failure: always
script:
- bundle exec rake default
- gem build sensu-plugins-php-fpm.gemspec
- gem install sensu-plugins-php-fpm-*.gem
deploy:
  provider: rubygems
  api_key:
    secure: K6x8cl/UqBU2XkuH71Y+NB3hDFVrUyQ+L+9Bu4AHjTxBOHo/r4IxEj6uccmbdvIytTop6e3J59BMTThGUSKS22grdouXH/0OTZDhWwV2SIs/BKgXpTH/xZJIlB2z0PCFCvEwcW7D/07asIScUYLmuZEHiyZ5t7xpc3h704C7on4=
  gem: sensu-plugins-php-fpm
  on:
    tags: true
    all_branches: true
    rvm: 2.0
    rvm: 2.1
    rvm: 2.2
    rvm: 2.3.0
    rvm: 2.4.1
    repo: sensu-plugins/sensu-plugins-php-fpm
